name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
          - name: get code
            uses: actions/checkout@v4
#            run:  |
#              echo "cloning repo" 
#              echo "${{toJson(github)}}"   
#              git clone https://github.com/${{github.repository}}.git

          - name: Install node 20
            uses: actions/setup-node@v4
            with:
              node-version: 21
	  - name: print node version
            run: node -v
	  - name: Install Dependencies 
            run: npm ci
          - name: run tests
            run: pm run test
